name: Pull Request

on:
  pull_request:
    branches: [ '**' ]

jobs:
  check-out-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  fake-dependent-step:
    runs-on: ubuntu-latest
    needs: check-out-code
    steps:
      - name: Fake doing some work
        run: echo "I did some work!"

  # this is here as we need to the logical and of three conditions (status checks passed & PR approved & mergable)
  final-sync-check:
    needs: fake-dependent-step
    name: Check if manual ArgoCD sync is required
    uses: ./.github/workflows/manual-sync-reminder.yaml
